Use legacy_connection_handling option only when it exists
```
  1) ActiveRecord::DebugErrors::DisplayConnectionOwners#execute when ActiveRecord::Deadlocked occurs when the user has the permission to execute 'SHOW ENGINE INNODB STATUS' displays latest detected deadlock
     Failure/Error: ActiveRecord::Base.legacy_connection_handling = false

     NoMethodError:
       undefined method `legacy_connection_handling=' for class ActiveRecord::Base
     # ./vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
     # ./spec/spec_helper.rb:29:in `block (2 levels) in <top (required)>'
```